# Generated by Django 5.0.3 on 2025-03-21 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.CharField(choices=[('Uncategorized', 'Uncategorized'), ('Business', 'Business'), ('Family', 'Family'), ('Friends', 'Friends'), ('Personal', 'Personal')], default='Uncategorized', max_length=20),
        ),
    ]
