# Generated by Django 5.0.3 on 2025-03-29 10:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tagged_users',
            field=models.ManyToManyField(blank=True, related_name='tagged_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.CharField(choices=[('Uncategorized', 'Uncategorized'), ('Business', 'Business'), ('Family', 'Family'), ('Friends', 'Friends'), ('Personal', 'Personal'), ('Tagged', 'Tagged')], default='Uncategorized', max_length=20),
        ),
    ]
